jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v3

    # Ensure terajdbc jar is in the correct location for the build
    - name: Setup terajdbc jar for build
      run: |
        # Check if the terajdbc jar exists in the expected location, and copy if necessary
        if [ ! -f ./libs/terajdbc-20.00.00.06.jar ]; then
          echo "terajdbc jar is missing in ./libs/ directory"
          exit 1
        fi
        # No need to copy if it's already in the right place
        echo "terajdbc jar is found and ready for build"

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Set up JDK 1.8
      uses: actions/setup-java@v3
      with:
        distribution: 'zulu'
        java-version: 8

    - name: Build with Maven
      run: mvn -B clean package -DskipTests

    - name: Stamp artifact file name with commit hash
      run: |
        artifactName1=$(ls target/*.jar | head -1)
        commitHash=$(git rev-parse --short "$GITHUB_SHA")
        artifactName2=$(echo "$artifactName1" | sed "s/.jar/-$commitHash.jar/")
        mv "$artifactName1" "$artifactName2"

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: mule-artifact
        path: target/*.jar

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
    - name: Checkout this repo
      uses: actions/checkout@v3

    # Ensure terajdbc jar is available for the deploy step
    - name: Setup terajdbc jar for deploy
      run: |
        # Check if the terajdbc jar exists in the expected location, and copy if necessary
        if [ ! -f ./libs/terajdbc-20.00.00.06.jar ]; then
          echo "terajdbc jar is missing in ./libs/ directory"
          exit 1
        fi
        # No need to copy if it's already in the right place
        echo "terajdbc jar is found and ready for deploy"

    - name: Cache dependencies
      uses: actions/cache@v3
      with:
        path: ~/.m2/repository
        key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
        restore-keys: |
          ${{ runner.os }}-maven-

    - name: Download artifact
      uses: actions/download-artifact@v4
      with:
        name: mule-artifact
        path: .

    - name: Deploy to CloudHub
      run: |
        artifactName=$(ls *.jar | head -1)
        mvn deploy -DskipTests -DmuleDeploy \
          -Dmule.artifact="$artifactName" \
          -Dclient.id="${{ secrets.CONNECTED_APP_CLIENT_ID }}" \
          -Dclient.secret="${{ secrets.CONNECTED_APP_CLIENT_SECRET }}" \
          -Denv="${{ secrets.DEPLOY_ENV }}"
